language: node_js
node_js:
  - '8'

addons:
  firefox: latest

cache:
  yarn: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run linter
  - yarn run test
